/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminEntregadoresRouteImport } from './routes/admin.entregadores'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as CheckoutCustomerRouteImport } from './routes/checkout.customer'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as EntregadorIndexRouteImport } from './routes/entregador.index'
import { Route as EntregadorEntregasRouteImport } from './routes/entregador.entregas'
import { Route as EntregadorHistoricoRouteImport } from './routes/entregador.historico'
import { Route as EntregadorPerfilRouteImport } from './routes/entregador.perfil'
import { Route as EntregadorRotaRouteImport } from './routes/entregador.rota'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregadoresRoute = AdminEntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/checkout/address',
  path: '/checkout/address',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCustomerRoute = CheckoutCustomerRouteImport.update({
  id: '/checkout/customer',
  path: '/checkout/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/checkout/review',
  path: '/checkout/review',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorIndexRoute = EntregadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorEntregasRoute = EntregadorEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorHistoricoRoute = EntregadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorPerfilRoute = EntregadorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorRotaRoute = EntregadorRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => EntregadorRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/entregador': typeof EntregadorRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/entregador/': typeof EntregadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/entregador': typeof EntregadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/entregador': typeof EntregadorRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/entregador/': typeof EntregadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/entregador'
    | '/order-confirmed'
    | '/tracking'
    | '/admin/cardapio'
    | '/admin/config'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/whatsapp'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/admin/'
    | '/entregador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/order-confirmed'
    | '/tracking'
    | '/admin/cardapio'
    | '/admin/config'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/whatsapp'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/admin'
    | '/entregador'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/entregador'
    | '/order-confirmed'
    | '/tracking'
    | '/admin/cardapio'
    | '/admin/config'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/whatsapp'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/admin/'
    | '/entregador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  DriverRoute: typeof DriverRoute
  EntregadorRoute: typeof EntregadorRouteWithChildren
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  TrackingRoute: typeof TrackingRoute
  CheckoutAddressRoute: typeof CheckoutAddressRoute
  CheckoutCustomerRoute: typeof CheckoutCustomerRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregadores': {
      id: '/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AdminEntregadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/checkout/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/customer': {
      id: '/checkout/customer'
      path: '/checkout/customer'
      fullPath: '/checkout/customer'
      preLoaderRoute: typeof CheckoutCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/checkout/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador/': {
      id: '/entregador/'
      path: '/'
      fullPath: '/entregador/'
      preLoaderRoute: typeof EntregadorIndexRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/entregas': {
      id: '/entregador/entregas'
      path: '/entregas'
      fullPath: '/entregador/entregas'
      preLoaderRoute: typeof EntregadorEntregasRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/historico': {
      id: '/entregador/historico'
      path: '/historico'
      fullPath: '/entregador/historico'
      preLoaderRoute: typeof EntregadorHistoricoRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/perfil': {
      id: '/entregador/perfil'
      path: '/perfil'
      fullPath: '/entregador/perfil'
      preLoaderRoute: typeof EntregadorPerfilRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/rota': {
      id: '/entregador/rota'
      path: '/rota'
      fullPath: '/entregador/rota'
      preLoaderRoute: typeof EntregadorRotaRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminEntregadoresRoute: typeof AdminEntregadoresRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardapioRoute: AdminCardapioRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminEntregadoresRoute: AdminEntregadoresRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EntregadorRouteChildren {
  EntregadorEntregasRoute: typeof EntregadorEntregasRoute
  EntregadorHistoricoRoute: typeof EntregadorHistoricoRoute
  EntregadorPerfilRoute: typeof EntregadorPerfilRoute
  EntregadorRotaRoute: typeof EntregadorRotaRoute
  EntregadorIndexRoute: typeof EntregadorIndexRoute
}

const EntregadorRouteChildren: EntregadorRouteChildren = {
  EntregadorEntregasRoute: EntregadorEntregasRoute,
  EntregadorHistoricoRoute: EntregadorHistoricoRoute,
  EntregadorPerfilRoute: EntregadorPerfilRoute,
  EntregadorRotaRoute: EntregadorRotaRoute,
  EntregadorIndexRoute: EntregadorIndexRoute,
}

const EntregadorRouteWithChildren = EntregadorRoute._addFileChildren(
  EntregadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  DriverRoute: DriverRoute,
  EntregadorRoute: EntregadorRouteWithChildren,
  OrderConfirmedRoute: OrderConfirmedRoute,
  TrackingRoute: TrackingRoute,
  CheckoutAddressRoute: CheckoutAddressRoute,
  CheckoutCustomerRoute: CheckoutCustomerRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
