/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as CheckoutCustomerRouteImport } from './routes/checkout.customer'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as EntregadorIndexRouteImport } from './routes/entregador.index'
import { Route as EntregadorEntregasRouteImport } from './routes/entregador.entregas'
import { Route as EntregadorHistoricoRouteImport } from './routes/entregador.historico'
import { Route as EntregadorPerfilRouteImport } from './routes/entregador.perfil'
import { Route as EntregadorRotaRouteImport } from './routes/entregador.rota'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/checkout/address',
  path: '/checkout/address',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCustomerRoute = CheckoutCustomerRouteImport.update({
  id: '/checkout/customer',
  path: '/checkout/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/checkout/review',
  path: '/checkout/review',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorIndexRoute = EntregadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorEntregasRoute = EntregadorEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorHistoricoRoute = EntregadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorPerfilRoute = EntregadorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => EntregadorRoute,
} as any)
const EntregadorRotaRoute = EntregadorRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => EntregadorRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/entregador': typeof EntregadorRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/entregador/': typeof EntregadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/entregador': typeof EntregadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/driver': typeof DriverRoute
  '/entregador': typeof EntregadorRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tracking': typeof TrackingRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/customer': typeof CheckoutCustomerRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/entregador/entregas': typeof EntregadorEntregasRoute
  '/entregador/historico': typeof EntregadorHistoricoRoute
  '/entregador/perfil': typeof EntregadorPerfilRoute
  '/entregador/rota': typeof EntregadorRotaRoute
  '/product/$id': typeof ProductIdRoute
  '/entregador/': typeof EntregadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/entregador'
    | '/order-confirmed'
    | '/tracking'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/entregador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/order-confirmed'
    | '/tracking'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/entregador'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/driver'
    | '/entregador'
    | '/order-confirmed'
    | '/tracking'
    | '/checkout/address'
    | '/checkout/customer'
    | '/checkout/payment'
    | '/checkout/review'
    | '/entregador/entregas'
    | '/entregador/historico'
    | '/entregador/perfil'
    | '/entregador/rota'
    | '/product/$id'
    | '/entregador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  DriverRoute: typeof DriverRoute
  EntregadorRoute: typeof EntregadorRouteWithChildren
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  TrackingRoute: typeof TrackingRoute
  CheckoutAddressRoute: typeof CheckoutAddressRoute
  CheckoutCustomerRoute: typeof CheckoutCustomerRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/checkout/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/customer': {
      id: '/checkout/customer'
      path: '/checkout/customer'
      fullPath: '/checkout/customer'
      preLoaderRoute: typeof CheckoutCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/checkout/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador/': {
      id: '/entregador/'
      path: '/'
      fullPath: '/entregador/'
      preLoaderRoute: typeof EntregadorIndexRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/entregas': {
      id: '/entregador/entregas'
      path: '/entregas'
      fullPath: '/entregador/entregas'
      preLoaderRoute: typeof EntregadorEntregasRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/historico': {
      id: '/entregador/historico'
      path: '/historico'
      fullPath: '/entregador/historico'
      preLoaderRoute: typeof EntregadorHistoricoRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/perfil': {
      id: '/entregador/perfil'
      path: '/perfil'
      fullPath: '/entregador/perfil'
      preLoaderRoute: typeof EntregadorPerfilRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/entregador/rota': {
      id: '/entregador/rota'
      path: '/rota'
      fullPath: '/entregador/rota'
      preLoaderRoute: typeof EntregadorRotaRouteImport
      parentRoute: typeof EntregadorRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EntregadorRouteChildren {
  EntregadorEntregasRoute: typeof EntregadorEntregasRoute
  EntregadorHistoricoRoute: typeof EntregadorHistoricoRoute
  EntregadorPerfilRoute: typeof EntregadorPerfilRoute
  EntregadorRotaRoute: typeof EntregadorRotaRoute
  EntregadorIndexRoute: typeof EntregadorIndexRoute
}

const EntregadorRouteChildren: EntregadorRouteChildren = {
  EntregadorEntregasRoute: EntregadorEntregasRoute,
  EntregadorHistoricoRoute: EntregadorHistoricoRoute,
  EntregadorPerfilRoute: EntregadorPerfilRoute,
  EntregadorRotaRoute: EntregadorRotaRoute,
  EntregadorIndexRoute: EntregadorIndexRoute,
}

const EntregadorRouteWithChildren = EntregadorRoute._addFileChildren(
  EntregadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  DriverRoute: DriverRoute,
  EntregadorRoute: EntregadorRouteWithChildren,
  OrderConfirmedRoute: OrderConfirmedRoute,
  TrackingRoute: TrackingRoute,
  CheckoutAddressRoute: CheckoutAddressRoute,
  CheckoutCustomerRoute: CheckoutCustomerRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
